name: ci
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_CID: ${{ secrets.SF_SAML_API_KEY }}
      BATON_COMPANY_ID: ${{ secrets.SF_COMPANY_ID }}
      BATON_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
      BATON_ISSUER_URL: ${{ secrets.SF_ISSUER_URL }}
      BATON_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
      BATON_PUBLIC_KEY: ${{ secrets.SF_PUBLIC_KEY }}
      BATON_SAML_API_KEY: ${{ secrets.SF_SAML_API_KEY }}
      BATON_SUBJECT_NAME_ID: ${{ secrets.SF_SUBJECT_NAME_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-successfactors
        run: go build ./cmd/baton-successfactors
      - name: Run baton-successfactors
        run: ./baton-successfactors
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin
      - name: Test baton resources
        env:
          BATON: baton
          BATON_SUCCESSFACTORS: ./baton-successfactors
          BATON_CID: ${{ secrets.SF_SAML_API_KEY }}
          BATON_COMPANY_ID: ${{ secrets.SF_COMPANY_ID }}
          BATON_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
          BATON_ISSUER_URL: ${{ secrets.SF_ISSUER_URL }}
          BATON_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
          BATON_PUBLIC_KEY: ${{ secrets.SF_PUBLIC_KEY }}
          BATON_SAML_API_KEY: ${{ secrets.SF_SAML_API_KEY }}
          BATON_SUBJECT_NAME_ID: ${{ secrets.SF_SUBJECT_NAME_ID }}
          BATON_PRINCIPAL: "rsmith"
        run: ./test/verify-resources.sh
