name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go tests
        run: (set -o pipefail && go test -v -covermode=count -json ./... | tee test.json)
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json

  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      $BATON_CID: ${{ secrets.SF_SAML_API_KEY }}
      $BATON_COMPANY_ID: ${{ secrets.SF_COMPANY_ID }}
      $BATON_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
      $BATON_ISSUER_URL: ${{ secrets.SF_ISSUER_URL }}
      $BATON_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
      $BATON_PUBLIC_KEY: ${{ secrets.SF_PUBLIC_KEY }}
      $BATON_SAML_API_KEY: ${{ secrets.SF_SAML_API_KEY }}
      $BATON_SUBJECT_NAME_ID: ${{ secrets.SF_SUBJECT_NAME_ID }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-successfactors
        run: go build ./cmd/baton-successfactors
      - name: Run baton-successfactors
        run: ./baton-successfactors
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin

